### ISSUE TITLE
Entire screen screenshot does not work as expected

### ISSUE THREAD

**Issue by alaa007** [fastaddons/Easy-Screenshot-for-Safari#1]
**Describe the bug**  
Entire screen screenshot does not work as expected

I will request a refund.

**Comment by fastaddons** [comment]
You've paid for it? It's free for everyone:
![image](https://user-images.githubusercontent.com/55486931/225000854-c7e95637-f9ff-4387-bc5f-276a131016de.png)

Are you sure you are using my addon?
Also, could you post the page where it didn't worked? I could look into it.

**Comment by alaa007** [comment]
Im super sorry! wrong repo! 
Please feel free to delete my issue.

Sorry again!

**Comment by fastaddons** [comment]
No problem :)
